### ISSUE TITLE
commands not working for the number which we installed

### ISSUE THREAD

**Issue by gokulapap** [phaticusthiccy/WhatsAsenaDuplicated#110]
2021-06-19T17:26:29.549432+00:00 app[worker.1]:         else if (killspam > 0.6 && !match[1].includes('killspam')) { return await message.client.sendMessage(id,LANG.RES + ' $killspam', MessageType.text) }

2021-06-19T17:26:29.549434+00:00 app[worker.1]:              ^

2021-06-19T17:26:29.549434+00:00 app[worker.1]: 

2021-06-19T17:26:29.549435+00:00 app[worker.1]: ReferenceError: killspam is not defined

2021-06-19T17:26:29.549436+00:00 app[worker.1]:     at Object.function (/root/WhatsAsenaDuplicated/plugins/web.js:293:14)

2021-06-19T17:26:29.549436+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)

2021-06-19T17:26:29.549437+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:93:5)

2021-06-19T17:26:29.549438+00:00 app[worker.1]:     at async /root/WhatsAsenaDuplicated/bot.js:496:46

2021-06-19T17:26:29.568771+00:00 app[worker.1]: Sat Jun 19 2021 20:26:29 GMT+0300 (GMT+03:00)

2021-06-19T17:26:29.570249+00:00 app[worker.1]: Program node bot.js exited with code 1

Getting this as a error when i try to execute admin commands from my number , it is working for other users who are executing general commands

**Comment by phaticusthiccy** [comment]
Closed. Issue has been resolved.
