### ISSUE TITLE
Bot is not working fine

### ISSUE THREAD

**Issue by rishabh-modi2** [phaticusthiccy/WhatsAsenaDuplicated#223]
**Describe the bug**
I deployed your awsome whatsapp bot on heroku but it workes fine if I use it in my login no. But whrn ever I type any command in any group or chat it restarts
I deployed 3 times but behaviour is same#

##

**Users, please complete the following actions.**
- WhatApp Package Name
- WhatsAsena Version #:-1: latest
- Work Type (Private)

##

**Additional context**

Your Bot is Awsome

**Comment by rishabh-modi2** [comment]
Here is the heroku logs


2021-11-19T12:32:52.354339+00:00 app[worker.1]: WhatsAsena
2021-11-19T12:32:52.354349+00:00 app[worker.1]: Version: v1.3.6 Global Stable
2021-11-19T12:32:52.354350+00:00 app[worker.1]: 
2021-11-19T12:32:52.354350+00:00 app[worker.1]: ℹ️ Connecting to WhatsApp... Please Wait.
2021-11-19T12:32:52.814723+00:00 app[worker.1]: ✅ Login Information Updated!
2021-11-19T12:32:52.817664+00:00 app[worker.1]: ✅ Login Successful!
2021-11-19T12:32:52.817767+00:00 app[worker.1]: ⬇️ Installing External Plugins...
2021-11-19T12:32:52.835254+00:00 app[worker.1]: ⬇️  Installing Plugins...
2021-11-19T12:32:53.392691+00:00 app[worker.1]: ✅ Plugins Installed!
2021-11-19T12:32:53.597352+00:00 app[worker.1]: 🐺 WhatsAsena Private
2021-11-19T12:33:41.223150+00:00 app[worker.1]: /root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:190
2021-11-19T12:33:41.223171+00:00 app[worker.1]:                 onErr = ({ reason, status }) => reject(new Constants_1.BaileysError(reason, { status }));
2021-11-19T12:33:41.223172+00:00 app[worker.1]:                                                        ^
2021-11-19T12:33:41.223172+00:00 app[worker.1]: 
2021-11-19T12:33:41.223173+00:00 app[worker.1]: BaileysError: Not expecting a response
2021-11-19T12:33:41.223173+00:00 app[worker.1]:     at onErr (/root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:190:56)
2021-11-19T12:33:41.223174+00:00 app[worker.1]:     at /root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:185:82
2021-11-19T12:33:41.223174+00:00 app[worker.1]:     at Timeout.<anonymous> (/root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:272:21)
2021-11-19T12:33:41.223174+00:00 app[worker.1]:     at listOnTimeout (node:internal/timers:556:17)
2021-11-19T12:33:41.223175+00:00 app[worker.1]:     at processTimers (node:internal/timers:499:7) {
2021-11-19T12:33:41.223175+00:00 app[worker.1]:   status: 422,
2021-11-19T12:33:41.223176+00:00 app[worker.1]:   context: { status: 422 }
2021-11-19T12:33:41.223176+00:00 app[worker.1]: }
2021-11-19T12:33:41.230828+00:00 app[worker.1]: Fri Nov 19 2021 15:33:41 GMT+0300 (GMT+03:00)
2021-11-19T12:33:41.230908+00:00 app[worker.1]: Program node bot.js exited with code 1
2021-11-19T12:33:41.230909+00:00 app[worker.1]: 
2021-11-19T12:33:41.230933+00:00 app[worker.1]: Starting child process with 'node bot.js'
2021-11-19T12:33:42.518936+00:00 app[worker.1]: Loading EN language...
2021-11-19T12:33:42.700720+00:00 app[worker.1]: WhatsAsena
2021-11-19T12:33:42.700722+00:00 app[worker.1]: Version: v1.3.6 Global Stable
2021-11-19T12:33:42.700724+00:00 app[worker.1]: 
2021-11-19T12:33:42.700725+00:00 app[worker.1]: ℹ️ Connecting to WhatsApp... Please Wait.
2021-11-19T12:33:43.208742+00:00 app[worker.1]: ✅ Login Information Updated!
2021-11-19T12:33:43.211584+00:00 app[worker.1]: ✅ Login Successful!
2021-11-19T12:33:43.211632+00:00 app[worker.1]: ⬇️ Installing External Plugins...
2021-11-19T12:33:43.227830+00:00 app[worker.1]: ⬇️  Installing Plugins...
2021-11-19T12:33:43.817636+00:00 app[worker.1]: ✅ Plugins Installed!
2021-11-19T12:33:44.271357+00:00 app[worker.1]: 🐺 WhatsAsena Private
